//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWeb2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtencionVeterinaria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AtencionVeterinaria()
        {
            this.ControlDesparacitaciones = new HashSet<ControlDesparacitaciones>();
            this.ControlVacuna = new HashSet<ControlVacuna>();
            this.ExamenClinico = new HashSet<ExamenClinico>();
        }
    
        public int Id { get; set; }
        public string Usuario { get; set; }
        public int Sucursal { get; set; }
        public Nullable<int> IdMascota { get; set; }
        public Nullable<int> Microchip { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Sucursal Sucursal1 { get; set; }
        public virtual Mascota Mascota { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlDesparacitaciones> ControlDesparacitaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ControlVacuna> ControlVacuna { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamenClinico> ExamenClinico { get; set; }
    }
}
