//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWeb2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlVacuna
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ControlVacuna()
        {
            this.AtencionVeterinaria = new HashSet<AtencionVeterinaria>();
        }
    
        public int Id { get; set; }
        public double Temperatura { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime ProximaFecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Dosis { get; set; }
        public string ViaAdministracion { get; set; }
        public string Vacuna { get; set; }
        public Nullable<int> IdMascota { get; set; }
        public Nullable<int> Microchip { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtencionVeterinaria> AtencionVeterinaria { get; set; }
        public virtual Mascota Mascota { get; set; }
    }
}
