//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWeb2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ControlDesparacitaciones
    {
        public int Id { get; set; }
        public int Atencion { get; set; }
        public double Peso { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime ProximaFecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string Vacuna { get; set; }
        public string Dosis { get; set; }
        public string ViaAdministracion { get; set; }
    
        public virtual AtencionVeterinaria AtencionVeterinaria { get; set; }
    }
}
