//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWeb2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Defuncion
    {
        public int Id { get; set; }
        public string ObservacionDefuncion { get; set; }
        public string CausaDefuncion { get; set; }
        public Nullable<System.DateTime> FechaDefuncion { get; set; }
        public string Defuncion1 { get; set; }
        public Nullable<int> MascotaId { get; set; }
        public Nullable<int> MascotaMicrochip { get; set; }
    
        public virtual Mascota Mascota { get; set; }
    }
}
