//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWeb2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamenClinico
    {
        public int Id { get; set; }
        public int Atencion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string MotivoConsulta { get; set; }
        public int FrecuenciaCardiaca { get; set; }
        public double TemperaturaPaciente { get; set; }
        public string Anamnesis { get; set; }
        public string Diagnostico { get; set; }
        public string Tratamiento { get; set; }
        public string Tipo { get; set; }
    
        public virtual AtencionVeterinaria AtencionVeterinaria { get; set; }
    }
}
