//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWeb2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mascota
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mascota()
        {
            this.AtencionVeterinaria = new HashSet<AtencionVeterinaria>();
        }
    
        public int Id { get; set; }
        public int Microchip { get; set; }
        public Nullable<int> IdCliente { get; set; }
        public Nullable<int> RutCliente { get; set; }
        public int Especie { get; set; }
        public string Nombre { get; set; }
        public string Sexo { get; set; }
        public double Peso { get; set; }
        public string Color { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public byte[] Foto { get; set; }
        public string CausaDefuncion { get; set; }
        public string ObservacionDefuncion { get; set; }
        public System.DateTime FecheDefuncion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AtencionVeterinaria> AtencionVeterinaria { get; set; }
        public virtual DueñoMascota DueñoMascota { get; set; }
        public virtual Especie Especie1 { get; set; }
    }
}
