//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWeb2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_ControlDesparacitacion
    {
        public int Id { get; set; }
        public System.DateTime Fecha_Modificación { get; set; }
        public System.TimeSpan Hora_Modificación { get; set; }
        public string Nombre { get; set; }
        public string Descripción { get; set; }
        public string Via_Administracion { get; set; }
        public string Dosis { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.DateTime ProximaFecha { get; set; }
    }
}
