//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWeb2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_Defunciones
    {
        public string Nombre_Dueño { get; set; }
        public string Apellido_Dueño { get; set; }
        public int Rut_Dueño { get; set; }
        public int Numero_Microchip { get; set; }
        public string Nombre_Mascota { get; set; }
        public string Observacion_Defuncion { get; set; }
        public string Causa_defuncion { get; set; }
        public Nullable<System.DateTime> Fecha_Defuncion { get; set; }
        public string Defuncion { get; set; }
    }
}
