//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetWeb2._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_NuevaFicha
    {
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public int Rut { get; set; }
        public int Fono_Contacto { get; set; }
        public string Region { get; set; }
        public string Ciudad { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public string Nombre_Mascota { get; set; }
        public int Microchip { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public double Peso { get; set; }
        public string Sexo { get; set; }
        public string Tipo { get; set; }
        public string Raza { get; set; }
    }
}
